### PR TITLE
Avoid showing the JS code when GA tracker is not defined

### PR DESCRIPTION
**Pull request by chalofa**

### CODE REVIEW

**Comment by chalofa** [comment]
with Rails 6, in the system tests, I'm seeing all these Google Analytics extra events as page content:
image

Not exactly sure what Rails change caused this issue, but before Rails v6, the tests rendered those GA events as:

Rails 5.2:
```
<head>
...
<script type="text/javascript">
  ga("ec:setAction","checkout",{"step":"1"});
  ga("ec:addImpression",...
  ga(...)
</script>
</head>
<body>
...
</body>
```
(note the lack of the GA snippet, but at least, everything is wrapped in a `<script>` tag


in Rails 6:
```
<head>
...
ga("ec:setAction","checkout",{"step":"1"});
ga("ec:addImpression",...
ga(...)
</head>
<body>
...
</body>
```

there's no `<script>` that wraps that JS code, and therefore, the browser just shows it as visible text...

the change in this PR ensures that if there's no GA `tracker`, nothing will be rendered (which is the workaround that I'm using right now to avoid this: ensuring `rack-tracker` is disabled for the test environment)

**Comment by chalofa** [comment]
@DonSchado looks like you are pretty active with this Google Analytics tracker... if you can take a look at this PR, I would appreciate it...

probably way easier to see without all those whitespace changes:
https://github.com/railslove/rack-tracker/pull/149/files?w=1

**Comment by DonSchado** [comment]
I don't get the diff... is this just a change of indentation? Or also a scope change?

**Comment by chalofa** [comment]
> I don't get the diff... is this just a change of indentation? Or also a scope change?

basically, wrap the whole `<script>` tag inside the top `if tracker`...

**Comment by DonSchado** [comment]
hm wasn't that already fixed here: https://github.com/railslove/rack-tracker/commit/f3d4e65dee9527136c7613940f5cee16fba91f88 ? 
Sorry I'm confused

**Comment by chalofa** [comment]
> hm wasn't that already fixed here: [f3d4e65](https://github.com/railslove/rack-tracker/commit/f3d4e65dee9527136c7613940f5cee16fba91f88) ?
> Sorry I'm confused

@DonSchado nope, the indentation is totally messed up, see this image:

image

I added some indentation so it's easier to see the nested ifs, and move the whole template inside the `if tracker` conditional, so if no tracker is defined, it  won't render those events that are outside that conditional

**Comment by DonSchado** [comment]
Ah I see. Thanks for taking the time! 
Very appreciated :)

**Pull request merged**
