### PR TITLE
add parameters to mastertag

### PR DESCRIPTION
**Pull request by berlintam**
Looks like the mastertag also needs parameters...

sorry for all the fix PRs :(

### CODE REVIEW

**Comment by salimhb** [comment]
improvements are always welcome :)
Hope this plays well after merging #45

**Comment by berlintam** [comment]
I think it'll be fine. I have them both merged in my master branch & things aren't breaking or anything. Might be a small merge conflict but nothing crazy.

**Comment by salimhb** [comment]
@berlintam seems like it didn't work out, can you make this mergeable again?

**Comment by berlintam** [comment]
will do!

**Pull request merged**
