### PR TITLE
let travis test agains multiple gemfiles

### PR DESCRIPTION
**Pull request by salimhb**

### CODE REVIEW

**Comment by kangguru** [comment]
:rocket: super cool

**Comment by DonSchado** [comment]
woah, it's that easy! :) cool

**Comment by kangguru** [comment]
we should add some more!!! test all the versions! ;)

**Comment by kangguru** [comment]
can the Gemfile.locks maybe placed under `spec`? or is this a anti pattern?

**Comment by salimhb** [comment]
yeah really nice, of course this is failing with the 3.2 version.
About .locks, they are not needed, the multiple gemfiles target specific versions.
I do however have my doubt about naming them Gemfile.**rails**-3.2, what do you think about that?

**Comment by kangguru** [comment]
ah yea, sure no locks, but i mean the gemfiles itself, sry.

naming them with `rails-xxx` appears strange as there's not rails i it at all ;) just activesupport. but looks like nick is doing the same https://github.com/apotonick/roar-rails/blob/master/gemfiles/Gemfile.rails4-1

**Comment by bumi** [comment]
:+1:

**Comment by DonSchado** [comment]
ok, so we merge this after https://github.com/railslove/rack-tracker/pull/41

**Comment by salimhb** [comment]
yep, when it's all green

**Comment by DonSchado** [comment]
:party:

**Pull request merged**
