### PR TITLE
Facebook pixel

### PR DESCRIPTION
**Pull request by jolim**
With all credit going to @amclelland, this seems to work. It includes support for Turbolinks.

### CODE REVIEW

**Comment by DonSchado** [comment]
Awesome! 💚

**Comment by jolim** [comment]
Is it time to drop support for ruby < 2.0? It appears that the mime-types gem has done so.

https://rubygems.org/gems/mime-types

**Comment by DonSchado** [comment]
do it!

**Comment by jolim** [comment]
@DonSchado The only way to make the tests pass is to limit it to ruby >= 2.0 and to get rid of jruby. It's because of the mime-types-data, which doesn't support jruby.

The ruby version has nothing to do with this PR - it's baked into master already. Unless someone has a fix for master, the gem will be stalled unless we drop that requirement.

**Comment by bumi** [comment]
whooot! thanks again and it is finally in master! \o/
any feedback on the facebook tracking would be awesome as I am currently not using it myself.

**Pull request merged**
