### PR TITLE
Support magic frozen string literal

### PR DESCRIPTION
**Pull request by DonSchado**
297hzh

### CODE REVIEW

**Comment by DonSchado** [comment]
I have the strong feeling `GoogleTagManager#inject` is not well tested 🤔

**Comment by DonSchado** [comment]
Oh, nearly forgot too... we need to adjust/write some specs first. I believe this is otherwise "broken" at the moment. 🤔 but have also no time at the moment to look into it

**Comment by bumi** [comment]
do we? specs are green, aren't they?

**Comment by DonSchado** [comment]
yes. because my bet is that `GoogleTagManager#inject` is not covered 😬

**Pull request closed without merging**
