### PR TITLE
make use of pry-byebug but not on travis

### PR DESCRIPTION
**Pull request by jhilden**

### CODE REVIEW

**Comment by kangguru** [comment]
whats not good enough with `pry`?

**Comment by jhilden** [comment]
e.g. you can't continue execution with `c` shortcut

**Comment by jhilden** [comment]
it would make a big difference for me.  if there are no strong reasons against it.

**Comment by kangguru** [comment]
no merge from me, maybe @DonSchado has an opinion about this. putting bindings where i need them is good enough for me. and doing this Gemfile dance just because of Travis... i don't like it

**Comment by DonSchado** [comment]
Yes I have an opinion. 
Pry alone makes no good full debugger. IMO that's what gems like  
`pry-byebug ` , `pry-stack_explorer` and `pay-rescue` bring to the party. 
Pry has so much more good stuff to offer then binding.pry. 

FYI: there was some evolutionary transition: (pry-nav => pry-debugger  => pry-byebug) 

so in generell :+1: 

but... I don't understand the "gemfile dance" either. Why not just dev dependency, and all are happy?

**Comment by kangguru** [comment]
i'm a fan of BYOD (bring your own debugger) i even don't like having `pry`
as a dependency.

**Comment by DonSchado** [comment]
k, good argument. what's your workflow to BYOD? every time you need one, bundle?

**Comment by kangguru** [comment]
yep

**Comment by jhilden** [comment]
but besides debugging, you must also require the debugger in the spec_helper, or?

**Comment by jhilden** [comment]
btw:  it

**Comment by salimhb** [comment]
@DonSchado the gemfile dance is for travis because we're testing against ruby 1.9.3 too, with which pry-byebug is not compatible.

**Comment by kangguru** [comment]
and if you're trying to develop under 1.9.3 you're doomed :(

**Comment by salimhb** [comment]
right, let's stick to the byod workflow.

**Comment by salimhb** [comment]
@jhilden re: require in spec_helper, it's enough to require 'pry'

**Pull request closed without merging**
