### PR TITLE
Fix for adjusted_bounce_rate_timeouts

### LINKED ISSUE #48: Option adjusted_bounce_rate_timeouts is not working as explained
Generated javascript is 
```js
setTimeout(ga('send', 'event', '60_seconds', 'read'),60000);
```
while it should be

```js
setTimeout(function() { ga('send', 'event', '60_seconds', 'read'); },60000);
```

The former send the event when the page is loaded.

### PR DESCRIPTION
**Pull request by fabn**
This will fix #48

### CODE REVIEW

**Comment by DonSchado** [comment]
thx! :+1:

**Comment by DonSchado** [comment]
is it possible to test the behavior? so to have a failing spec this will fix?

**Comment by fabn** [comment]
The only way I see is to match the exact string (cleanest than regexp match). See if it's ok.

**Comment by DonSchado** [comment]
yeah, well first I was thinking of a "more integration like" test. 
But that would need a bigger test setup with phantomjs or something similar... 
maybe I'll add something for that in the future. 

thx again for your contribution! :)

**Pull request merged**
