### PR TITLE
Use local variables in rack middleware to prevent instance state changes

### PR DESCRIPTION
**Pull request by bumi**
see: https://github.com/railslove/rack-tracker/pull/150

### CODE REVIEW

**Comment by bumi** [comment]
@kspe @kangguru what do you think? can we merge this? I think such a fix should be released asap!

**Comment by kspe** [comment]
I'm only unsure about `@handlers` variable which is still there.

**Comment by bumi** [comment]
@DonSchado handlers should not have request state, do they?

@DonSchado @kangguru  can we either merge this one or #150 and release a new patch version?

**Comment by DonSchado** [comment]
because I'm not completely sure and don't have the time to investigate this further, maybe then we merge #150 because @kspe already know's that it works. :) ack?

**Comment by bumi** [comment]
then let's merge both. those instance variables for sure should not be there. And then we got the `dup` also in - not sure what that does to memory consumption, but we will see.

**Comment by kspe** [comment]
> not sure what that does to memory consumption, but we will see.

After deploying this change to prod we did not see any significant increase in memory usage (which was a bit surprising given this happens on each request). It might be this object is very lightweight and is garbage collected quite efficiently but I haven't done a detailed analysis of it.

**Comment by bumi** [comment]
ok, that's good to hear! thanks for that. 
@DonSchado ok? do you want to go ahead with both PRs and release a new patch? <3

**Comment by DonSchado** [comment]
new version released

**Pull request merged**
