### PR TITLE
Switched the tracker to always be stored in the session instead of it being swapped in and out of the env['tracker'].

### PR DESCRIPTION
**Pull request by jclusso**
See #152

### CODE REVIEW

**Comment by DonSchado** [comment]
@jclusso we released a new patch with some changes to internal state handling to make the middleware more thread safe. Could you incorporate the changes here as well? 👍

**Comment by jclusso** [comment]
@donschado, I’ll look into doing this later today.

**Comment by jclusso** [comment]
@DonSchado I merged the latest code on master into my branch.

**Comment by DonSchado** [comment]
@bumi what do you think? :)

**Comment by jclusso** [comment]
Closing this since we no longer use it.

**Pull request closed without merging**
